[build-system]
requires = [
    "setuptools>=61",
    "setuptools_scm[toml]>=7",
]
build-backend = "setuptools.build_meta"

[project]
name = "pretrained-dpa"  # Please revise this line.
dynamic = ["version"]
description = "A Pretrained DPA."  # Please revise this line.
authors = [
    { name = "Jinzhe Zeng", email = "jinzhe.zeng@ustc.edu.cn"},
]
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
]
dependencies = [
]
requires-python = ">=3.9"
readme = "README.md"
keywords = [
]

[project.scripts]
pretrained-dpa = "pretrained_dpa.cli:main"

[project.entry-points."deepmd.backend"]
pretrained = "pretrained_dpa.deepmd_backend:PretrainedBackend"

[project.urls]
repository = "https://github.com/njzjz/pretrained-dpa"  # Please revise this line.

[project.optional-dependencies]
test = [
    'pytest',
    'pytest-cov',
]

[tool.setuptools.packages.find]
include = ["pretrained_dpa*"]  # Please revise this line.

[tool.setuptools.package-data]
pretrained_dpa = ["models.json"]

[tool.setuptools_scm]
version_file = "pretrained_dpa/_version.py"  # Please revise this line.

[tool.ruff.lint]
select = [
    "ALL",
]
ignore = [
    "PLR0912",
    "PLR0913",
    "PLR0915",
    "PLR2004",
    "FBT001",
    "FBT002",
    "N803",
    "FA100",
    "S603",
    "ANN101",
    "ANN102",
    "C901",
    "E501",
    "D102",
    "TC003",
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.isort]
required-imports = [
    "from __future__ import annotations",
]

[tool.ruff.lint.extend-per-file-ignores]
"pretrained_dpa/deepmd_backend.py" = [
    "ANN401",
    "D102",
    "PLC0415",
]
"tests/**/*.py" = [
    "S101", # asserts allowed in tests...
    "ANN",
    "D101",
    "D102",
    "SLF001",
    "B010",
]

[tool.coverage.report]
include = ["pretrained_dpa/*"]  # Please revise this line.

[tool.mypy]

[[tool.mypy.overrides]]
module = ["deepmd", "deepmd.*"]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["pretrained_dpa.deepmd_backend"]
disable_error_code = ["attr-defined"]
